'use client';
import {useEffect,useState,type FormEvent} from 'react';
import ColumnMarkdown from './ColumnMarkdown';
import TimeGauge from './TimeGauge';
import PreparationTree from './PreparationTree';
import SamplePreview from './SamplePreview';
import type {PreparationProgress} from '../../../contracts/preparation';
import glossary from '../../../content/glossary.json';
type Assessment={id:string;status:string;receivedAt:number;consultationAt:number;demo:boolean;fallbackReason:string|null;progress:PreparationProgress|null};
type Timeline={id:string;kind:string;title:string;scheduledAt:number;status:string;answered:boolean;skipped:boolean;withGlossary:boolean};
type Item={id:string;title:string;body:string;question:null|{id:string;questionPrompt:string;options:{id:string;text:string}[];freeTextHint:string};response:null|{optionId:string;freeText:string;skipped:boolean};glossary:null|{title:string;body:string}};
async function gql(query:string,variables:Record<string,unknown>={}){const r=await fetch('/api/graphql',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,variables})});const data=await r.json();if(data.errors)throw new Error(data.errors[0].message);return data.data;}
const errorText=(e:unknown)=>{const code=(e as Error).message;return({INVALID_LOGIN:'이메일과 비밀번호를 확인해 주세요.',FORBIDDEN:'로그인 후 본인의 상담 준비를 조회해 주세요.',NOT_AVAILABLE:'아직 준비되지 않았거나 상담 일정이 종료된 콘텐츠입니다.',INVALID_INPUT:'입력 내용을 확인해 주세요.'} as Record<string,string>)[code]??'잠시 후 다시 시도해 주세요.'};
export default function CareApp(){
 const [user,setUser]=useState<string|null>(null),[email,setEmail]=useState('guardian1@example.test'),[password,setPassword]=useState('');
 const [samples,setSamples]=useState<any[]>([]),[sample,setSample]=useState('report-01'),[days,setDays]=useState(6),[demo,setDemo]=useState(true);
 const [assessments,setAssessments]=useState<Assessment[]>([]),[active,setActive]=useState<string|null>(null),[timeline,setTimeline]=useState<Timeline[]>([]),[item,setItem]=useState<Item|null>(null),[option,setOption]=useState(''),[text,setText]=useState('');
 const [creating,setCreating]=useState(false);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function refresh(){const data=await gql('query {assessments {id status receivedAt consultationAt demo fallbackReason progress{catalog ranking questions linking scheduling selectedColumnCount questionTotal questionCompleted questionFailed}}}');setAssessments(data.assessments);return data.assessments as Assessment[];}
 useEffect(()=>{gql('query {me {email}}').then(d=>setUser(d.me?.email??null)).catch(()=>{})},[]);
 useEffect(()=>{if(!user)return;gql('query {samples {id familyId name q featureSchemaVersion observationTopics consultationNote provenance}}').then(d=>setSamples(d.samples));refresh().then(a=>setActive(a[0]?.id??null)).catch(e=>setError(errorText(e)))},[user]);
 useEffect(()=>{if(!active||!user){setTimeline([]);return}let stopped=false;let timer:ReturnType<typeof setTimeout>|undefined;const poll=async()=>{let delay=2000;try{const d=await gql('query($id:ID!){careTimeline(assessmentId:$id){id kind title scheduledAt status answered skipped withGlossary} assessments{id status receivedAt consultationAt demo fallbackReason progress{catalog ranking questions linking scheduling selectedColumnCount questionTotal questionCompleted questionFailed}}}',{id:active});if(!stopped){setTimeline(d.careTimeline);setAssessments(d.assessments);delay=d.assessments.find((a:Assessment)=>a.id===active)?.status==='processing'?500:2000}}catch(e){if(!stopped)setError(errorText(e))}finally{if(!stopped)timer=setTimeout(poll,delay)}};poll();return()=>{stopped=true;clearTimeout(timer)}},[active,user]);
 async function signIn(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await gql('mutation($email:String!,$password:String!){login(email:$email,password:$password){email}}',{email,password});setUser(d.login.email);setPassword('')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function create(){setCreating(true);setBusy(true);setError('');setNotice('');try{const report=samples.find(r=>r.id===sample);const now=Date.now();const d=await gql('mutation($input:AssessmentInput!,$key:String!){createAssessment(input:$input,idempotencyKey:$key){id status}}',{input:{q:report.q,receivedAt:now,consultationAt:now+days*86400000,timezone:'Asia/Seoul',featureSchemaVersion:report.featureSchemaVersion,demo},key:crypto.randomUUID()});setActive(d.createAssessment.id);setTimeline([]);setItem(null);await refresh()}catch(e){setError(errorText(e))}finally{setBusy(false);setCreating(false)}}
 async function open(id:string){setBusy(true);setError('');setNotice('');try{const d=await gql('query($id:ID!){careItem(id:$id){id title body question{id questionPrompt options{id text} freeTextHint} glossary{title body} response{optionId freeText skipped}}}',{id});setItem(d.careItem);setOption(d.careItem.response?.optionId??'');setText(d.careItem.response?.freeText??'')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function save(skipped=false){if(!item?.question)return;setBusy(true);setError('');try{await gql(skipped?'mutation($m:ID!,$q:ID!){skipQuestion(messageId:$m,questionId:$q){id saved}}':'mutation($m:ID!,$q:ID!,$o:String!,$t:String){submitResponse(messageId:$m,questionId:$q,optionId:$o,freeText:$t){id saved}}',{m:item.id,q:item.question.id,...(!skipped?{o:option,t:text}:{})});setNotice(skipped?'질문을 건너뛰었습니다.':'응답을 저장했습니다.');await open(item.id);setNotice(skipped?'질문을 건너뛰었습니다.':'응답을 저장했습니다.')}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 const current=creating?undefined:assessments.find(a=>a.id===active),total=creating?0:timeline.filter(t=>t.kind==='column').length,completed=creating?0:timeline.filter(t=>t.answered).length;
 return <main><header><a className="brand" href="/">아맘때 <span>상담 준비</span></a><span className="chip">PoC · 합성 데이터</span>{user&&<button className="quiet" onClick={async()=>{await gql('mutation {logout}');setUser(null);setActive(null);setItem(null)}}>로그아웃</button>}</header>
 <div className="intro"><p className="eyebrow">상담까지의 시간을, 함께 준비해요</p><h1>작은 관찰이<br/>대화의 시작이 돼요.</h1><p>아이의 생활 장면을 살펴보고, 상담에서 나누고 싶은 이야기를 준비해 보세요.</p></div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {!user?<form className="panel login" onSubmit={signIn}><h2>상담 준비 로그인</h2><p>로컬 데모 계정과 비밀번호는 실행한 터미널에 표시됩니다.</p><label>이메일<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy} type="submit">{busy?'로그인 중…':'로그인'}</button></form>:
 <div className="columns"><aside><section className="panel"><h2>새로운 상담 준비</h2><label htmlFor="synthetic-report">합성 보고서</label><select id="synthetic-report" value={sample} onChange={e=>setSample(e.target.value)}>{samples.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><SamplePreview sample={samples.find(r=>r.id===sample)}/><label>상담까지 남은 날<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[1,2,3,6,10].map(d=><option key={d} value={d}>{d}일</option>)}</select></label><label className="check"><input type="checkbox" checked={demo} onChange={e=>setDemo(e.target.checked)}/>일정 단축 데모 (첫 카드 2초, 이후 15초 간격)</label><button disabled={busy||!samples.length} onClick={create}>상담 준비 시작</button><p className="small">보고서와 콘텐츠는 독립적으로 만든 데모입니다. 전문가 임상 검수를 받은 자료가 아닙니다.</p></section>
 <section className="panel"><h2>나의 준비 기록</h2>{!assessments.length&&<p>아직 시작한 준비가 없습니다.</p>}{assessments.map((a,i)=><button className={`record ${active===a.id?'selected':''}`} key={a.id} onClick={()=>{setActive(a.id);setTimeline([]);setItem(null)}}>준비 {assessments.length-i}<span>{new Date(a.consultationAt).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})} 상담</span></button>)}</section></aside>
 <section>{item?<article className="panel article"><button className="quiet" onClick={()=>{setItem(null);setNotice('')}}>← 준비 홈</button><p className="eyebrow">오늘의 관찰</p><h2>{item.title}</h2><ColumnMarkdown body={item.body}/>{item.glossary&&<details><summary>{item.glossary.title}</summary><p>{item.glossary.body}</p></details>}{item.question&&<div className="question"><h3>{item.question.questionPrompt}</h3>{item.question.options.map(o=><label className={`choice ${option===o.id?'picked':''}`} key={o.id}><input type="radio" name="observation" value={o.id} checked={option===o.id} disabled={!!item.response} onChange={()=>setOption(o.id)}/>{o.text}</label>)}<label>{item.question.freeTextHint}<textarea maxLength={1000} value={text} disabled={!!item.response} onChange={e=>setText(e.target.value)}/></label>{item.response?<p className="notice">{item.response.skipped?'건너뛴 질문입니다.':'응답이 저장되어 있습니다.'}</p>:<div className="actions"><button disabled={busy||!option} onClick={()=>save()}>응답 저장</button><button className="quiet" disabled={busy} onClick={()=>save(true)}>건너뛰기</button></div>}</div>}</article>:<section className="panel"><TimeGauge preparation={current} events={creating?[]:timeline}/><PreparationTree preparation={current} items={timeline} creating={creating}/><div className="title-row"><h2>우리 아이 상담 준비</h2>{current&&<span className="chip">{current.demo?'실제 D-':'D-'}{Math.max(0,Math.ceil((current.consultationAt-Date.now())/86400000))}</span>}</div><p>{completed}/{total} 질문 완료</p><progress aria-label="질문 완료" value={completed} max={Math.max(total,1)}/>{current?.status==='processing'&&<p role="status">관련 칼럼과 질문을 준비하고 있습니다…</p>}{current?.status==='degraded'&&<p className="small">{current.fallbackReason==='MOCK_FEATURE_PROVIDER'?'외부 AI feature는 mock으로 표시된 데모입니다. 추천 순위는 학습한 XGBRanker로 계산했습니다.':current.fallbackReason==='PERSONALIZED_QUESTION_FAILED'?'칼럼은 추천했지만 개인화 질문 생성에 실패해, 검토된 공통 질문을 준비했습니다.':current.fallbackReason==='RANKER_UNAVAILABLE'?'추천 서버 연결 문제로 검토된 기본 콘텐츠를 준비했습니다.':'일부 준비 과정에 문제가 있어 검토된 기본 자료를 사용합니다.'}</p>}{current?.status==='failed'&&<p role="alert">준비를 완료하지 못했습니다. 새 준비를 시작해 주세요.</p>}{!active&&<p className="empty">합성 보고서를 선택해 상담 준비를 시작해 보세요.</p>}{(creating?[]:timeline).map(t=><div className={`care-card ${t.status==='sent'?'ready':''}`} key={t.id}><p className="eyebrow">{t.answered?'응답 완료':t.skipped?'건너뜀':t.status==='sent'?'지금 읽을 수 있어요':'예정 콘텐츠'}</p><h3>{t.title}</h3><div className="title-row"><time>{new Date(t.scheduledAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</time><button disabled={t.status!=='sent'||busy} onClick={()=>open(t.id)}>{t.status==='sent'?'읽고 관찰하기':t.status==='failed'?'준비 실패':'준비 중'}</button></div></div>)}</section>}
 <details className="panel glossary"><summary>{glossary.title}</summary><p>{glossary.body}</p></details></section></div>}
 <footer>이 내용은 진단이 아니며, 정확한 해석은 상담사와 함께 확인해 주세요.</footer></main>
}
