import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
const credentials=JSON.parse(readFileSync('.runtime/demo-login.json','utf8'));
const sampleReports=JSON.parse(readFileSync('fixtures/synthetic/reports.json','utf8'));
test('login → ranked scheduled content → response → reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await page.getByLabel('이메일').fill(credentials.email);
 await page.getByLabel('비밀번호').fill(credentials.password);
 await page.getByRole('button',{name:'로그인',exact:true}).click();
 await expect(page.getByRole('heading',{name:'새로운 상담 준비'})).toBeVisible();
 await page.getByLabel('합성 보고서',{exact:true}).selectOption('report-02');
 const preview=page.getByRole('button',{name:'선택한 합성 사례 보기',exact:true});
 await preview.click();
 const dialog=page.getByRole('dialog',{name:'합성 사례 02',exact:true});
 await expect(dialog).toBeVisible();
 const labels=['주의집중 문제','총 문제행동','내재화','우울/불안','사회적 미성숙','위축'];
 for(const [index,label] of labels.entries()){
  await expect(dialog.getByRole('meter',{name:label,exact:true})).toHaveAttribute('aria-valuenow',String(sampleReports[1].q[index]));
  await expect(dialog.getByText(`q[${index}]`,{exact:true})).toBeVisible();
 }
 await dialog.locator('.sample-source summary').click();
 expect(JSON.parse(await dialog.locator('.sample-json code').innerText())).toEqual(sampleReports.find((r:any)=>r.id==='report-02'));
 await dialog.locator('.sample-source summary').click();
 await page.setViewportSize({width:390,height:844});
 await expect(dialog).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 expect(await dialog.evaluate(node=>node.scrollWidth<=node.clientWidth)).toBe(true);
 await page.screenshot({path:'.runtime/q-profile-mobile.png'});
 await page.keyboard.press('Escape');
 await expect(dialog).not.toBeVisible();
 await expect(preview).toBeFocused();
 await page.setViewportSize({width:1280,height:950});
 await page.getByLabel('합성 보고서',{exact:true}).selectOption('report-01');
 await preview.click();
 const firstDialog=page.getByRole('dialog',{name:'합성 사례 01',exact:true});
 await expect(firstDialog.getByRole('meter',{name:'주의집중 문제',exact:true})).toHaveAttribute('aria-valuenow','66');
 await expect(firstDialog.getByRole('meter',{name:'사회적 미성숙',exact:true})).toHaveCount(0);
 await expect(firstDialog.getByLabel('사회적 미성숙: 결측 (null)',{exact:true})).toBeVisible();
 await firstDialog.locator('.sample-source summary').click();
 expect(JSON.parse(await firstDialog.locator('.sample-json code').innerText())).toEqual(sampleReports[0]);
 await firstDialog.locator('.sample-source summary').click();
 await page.screenshot({path:'.runtime/q-profile-desktop.png'});
 await firstDialog.getByRole('button',{name:'닫기',exact:true}).click();
 await page.route('**/api/graphql',async route=>{if(route.request().postData()?.includes('createAssessment'))await new Promise(resolve=>setTimeout(resolve,1000));await route.continue()});
 await page.getByRole('button',{name:'상담 준비 시작',exact:true}).click();
 const tree=page.getByRole('region',{name:'콘텐츠 준비 과정',exact:true});
 await expect(tree).toBeVisible();
 await expect(tree).toHaveAttribute('aria-busy','true');
 await page.screenshot({path:'.runtime/preparation-tree-loading.png',fullPage:true});
 await expect(tree).toHaveAttribute('aria-busy','false',{timeout:20000});
 await expect(tree.getByRole('status')).toHaveText('상담 준비 완료');
 await tree.locator('summary').click();
 await expect(tree.locator('.tree-root')).not.toBeVisible();
 await expect(tree.getByRole('status')).toHaveText('상담 준비 완료');
 await page.screenshot({path:'.runtime/preparation-tree-collapsed.png',fullPage:true});
 await tree.locator('summary').press('Enter');
 await expect(tree.locator('.tree-root')).toBeVisible();
 const gaugeBox=await page.locator('.time-gauge').boundingBox(),treeBox=await tree.boundingBox();
 expect(treeBox!.y).toBeGreaterThanOrEqual(gaugeBox!.y+gaugeBox!.height);
 await page.screenshot({path:'.runtime/preparation-tree-desktop.png',fullPage:true});
 const gauge=page.getByRole('progressbar',{name:'상담 준비 시간선',exact:true});
 await expect(gauge).toBeVisible();
 await expect(page.getByText('가상 시간선',{exact:true})).toBeVisible();
 await expect.poll(async()=>Number(await gauge.getAttribute('aria-valuenow'))).toBeGreaterThan(0);
 await page.screenshot({path:'.runtime/time-gauge-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await expect(gauge).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'.runtime/time-gauge-mobile.png',fullPage:true});
 await expect(tree).toBeVisible();
 await page.screenshot({path:'.runtime/preparation-tree-mobile.png',fullPage:true});
 await page.setViewportSize({width:1280,height:950});
 await expect(page.getByRole('button',{name:'읽고 관찰하기'}).first()).toBeEnabled({timeout:20000});
 await page.getByRole('button',{name:'읽고 관찰하기'}).first().click();
 await expect(page.locator('.column-markdown p').first()).toBeVisible();
 await expect(page.locator('.article > h2')).toContainText(/아빠와의 놀이는|아이 성적에 집착해|부모가 자존감이 높으면/);
 await page.screenshot({path:'.runtime/markdown-column-desktop.png',fullPage:true});
 await page.locator('input[type=radio]').first().check();
 await page.locator('textarea').fill('오후에 함께 놀았던 장면을 상담 때 이야기하고 싶어요.');
 await page.getByRole('button',{name:'응답 저장',exact:true}).click();
 await expect(page.getByText('응답이 저장되어 있습니다.')).toBeVisible();
 await page.getByRole('button',{name:'← 준비 홈',exact:true}).click();
 await expect(page.getByText('1/3 질문 완료')).toBeVisible();
 await page.reload();
 await expect(page.getByText('1/3 질문 완료')).toBeVisible();
 await page.getByRole('button',{name:'읽고 관찰하기'}).first().click();
 await expect(page.locator('textarea')).toHaveValue('오후에 함께 놀았던 장면을 상담 때 이야기하고 싶어요.');
 await expect(page.locator('input[type=radio]').first()).toBeChecked();
 await page.screenshot({path:'.runtime/care-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('main')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'.runtime/care-mobile.png',fullPage:true});
 expect(errors).toEqual([]);
});
test('GraphQL isolation and idempotency through real Convex',async({request,playwright})=>{
 async function gql(client:any,query:string,variables:unknown={}){const r=await client.post('/api/graphql',{data:{query,variables}});return r.json()}
 const login='mutation($e:String!,$p:String!){login(email:$e,password:$p){email}}';
 await gql(request,login,{e:credentials.email,p:credentials.password});
 const now=Date.now();const variables={input:{q:[70,50,51,62,49,null],receivedAt:now,consultationAt:now+6*86400000,timezone:'Asia/Seoul',featureSchemaVersion:'v1',demo:true},key:`test-${now}`};
 const create='mutation($input:AssessmentInput!,$key:String!){createAssessment(input:$input,idempotencyKey:$key){id status}}';
 const first=await gql(request,create,variables),second=await gql(request,create,variables);expect(second.data.createAssessment.id).toBe(first.data.createAssessment.id);
 const conflict=await gql(request,create,{...variables,input:{...variables.input,q:[50,50,51,62,49,null]}});expect(conflict.errors[0].message).toBe('IDEMPOTENCY_CONFLICT');
 const other=await playwright.request.newContext({baseURL:process.env.WEB_URL??'http://localhost:3000'});
 await gql(other,login,{e:'guardian2@example.test',p:credentials.password});
 const denied=await gql(other,'query($id:ID!){assessment(id:$id){id status}}',{id:first.data.createAssessment.id});expect(denied.errors[0].message).toBe('FORBIDDEN');
 const unauth=await playwright.request.newContext({baseURL:process.env.WEB_URL??'http://localhost:3000'});
 expect((await gql(unauth,'query {samples{id}}')).errors[0].message).toBe('FORBIDDEN');
 await other.dispose();await unauth.dispose();
});
